### ISSUE TITLE
Is this a issue?

### ISSUE THREAD

**Issue by DEVAbdelToom** [NebulaServices/Dynamic#11]
`Request contains invalid range header:  [ '1616092', '1616092' ]
Error: Range request present but invalid, might serve whole file instead
    at Server.respondNoGzip (/home/runner/Dynamic-1/node_modules/node-static/lib/node-static.js:297:23)
    at Server.respond (/home/runner/Dynamic-1/node_modules/node-static/lib/node-static.js:350:14)
    at /home/runner/Dynamic-1/node_modules/node-static/lib/node-static.js:146:22
    at FSReqCallback.oncomplete (node:fs:208:5)
`

**Comment by GreenyDEV** [comment]
That is an issue with Node static, not Dynamic. You're likely attempting to use Dynamic on Replit

**Comment by cohenerickson** [comment]
Can this be closed?

**Comment by Riftriot** [comment]
fr

**Comment by cohenerickson** [comment]
Closed as stale.
